# Generated by Django 5.1.4 on 2025-04-14 17:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('making_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('refill_date', models.DateField(blank=True, null=True)),
                ('frequency_per_day', models.PositiveSmallIntegerField(default=1)),
                ('tablets_per_dose', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('remaining_tablets', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='making_profile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('tracking_data', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_tracking', to='making_profile.profile')),
            ],
        ),
    ]
