# Generated by Django 5.1.6 on 2025-03-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='remaining_tablets',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=5),
        ),
    ]
