# Generated by Django 5.1.6 on 2025-02-16 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='conditions',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='previous_medications',
        ),
        migrations.AddField(
            model_name='condition',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_conditions', to='making_profile.profile'),
        ),
        migrations.AddField(
            model_name='medication',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='making_profile.profile'),
        ),
    ]
