name: RxHarmony Deployment Check

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY_RECOMMEND: ${{ secrets.OPENAI_API_KEY_RECOMMEND }}
      OPENAI_API_KEY_DISCOUNT: ${{ secrets.OPENAI_API_KEY_DISCOUNT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up virtual environment and install Django
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install django

      - name: Merge conflicting migrations (non-interactive)
        run: |
          source venv/bin/activate
          DJANGO_SETTINGS_MODULE=RxHarmony.settings python manage.py makemigrations --merge --noinput

      - name: Run Django migrations
        run: |
          source venv/bin/activate
          python manage.py migrate

      - name: Run tests
        run: |
          source venv/bin/activate
          python manage.py test
